### ISSUE TITLE
这个项目是否还有更新的进展

### ISSUE THREAD

**Issue by Yecgaa1** [windowsair/wireless-esp32-dap#1]
我希望可以使用到ESP32的优势，在该项目基础上制作一个更多功能的无线调试器
我尝试把ESP8266的程序移植到ESP32上，但是这似乎比我想的要困难很多

**Comment by Yecgaa1** [comment]
我看develop分支似乎有所进展，但似乎一段时间未曾更新。我想了解一下目前该项目的进度和困难点

**Comment by windowsair** [comment]
develop分支是一个早期版本，可以直接使用

之后会更新的，等我有时间把几个项目合并一下

**Comment by Yecgaa1** [comment]
好的
